# Generated by Django 5.0.3 on 2024-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
